<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
  <testsuite failures="1" id="0" name="JUnitFormatter" package="cucumber.runtime.formatter" skipped="0" tests="1" time="0.166868">
    <testcase classname="secsuite" name="secsuitecase" time="0.166868">
      <failure message="java.lang.AssertionError: expected:&lt;1&gt; but was:&lt;2&gt;&#xa;&#x9;at org.junit.Assert.fail(Assert.java:88)&#xa;&#x9;at org.junit.Assert.failNotEquals(Assert.java:743)&#xa;&#x9;at org.junit.Assert.assertEquals(Assert.java:118)&#xa;&#x9;at org.junit.Assert.assertEquals(Assert.java:555)&#xa;&#x9;at org.junit.Assert.assertEquals(Assert.java:542)&#xa;&#x9;at StepDefinitions.получить_результат(Unknown Source)&#xa;&#x9;at ✽.* get result(test/resources/page_functionality.feature:7)&#xa;"><![CDATA[* open page "hello".........................................................passed
* open page "hello".........................................................passed
* open page "hello".........................................................passed
* get result................................................................failed

StackTrace:
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at StepDefinitions.получить_результат(Unknown Source)
	at ✽.* get result(test/resources/page_functionality.feature:7)
]]></failure>

    </testcase>

  </testsuite>
</testsuites>
